### ISSUE TITLE
Regression: positional specifiers (%1$s) in String.format make iOS app crash

### ISSUE THREAD

**Issue by ferdi2005** [tidev/titanium-sdk#13559]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Using a positional specifier like `%1$s `and `%2$s` with `String.format` makes the app crash, only on iOS, while on Android it works fine. The first version I've noticed this behaviour with is 11.1.0.GA. While I cannot exclude that a previous version had this problem, I can confirm that in the past it worked fine using the exact same code.

See the crash report here: https://gist.github.com/ferdi2005/37c1a3429d9161da7c719d8006ad00eb

### Expected Behavior

`String.format("Username: %1$s Wiki: %2$s", "a", "b");` should result in `Username: a Wiki: b`

### Actual behavior

Only on iOS, the app crashes.

### Reproducible sample

`String.format("Username: %1$s Wiki: %2$s", "a", "b");` wherever you want, on iOS

### Steps to reproduce

1. Try to use string format with positional specifiers (as in the examples above).
2. The app crashes.

### Platform

iOS

### SDK version you are using

11.1.0.GA

### Alloy version you are using

2.0.1

**Comment by de1mat** [comment]
This needs fixing pretty urgently as it is used inside my translation files - I can't just remove the positional specifiers as shown in the workaround as this will not work in translated strings where the position is different.

**Comment by m1ga** [comment]
That part hasn't been touched in ages:

https://github.com/tidev/titanium_mobile/blame/81d3f4a1bfa69a5367b8cf05af40b608b62ebe3b/iphone/TitaniumKit/TitaniumKit/Sources/Kroll/KrollContext.m#L825-L829

But this might be the place to dig around

**Comment by RavindraChherke** [comment]
When I build the app with SDK 11.1.1 GA with Xcode 13 then it works fine but when I build the app with Xcode 14 then weird output on screen.

```
<string name="shop_card_number_ending_with" formatted="false">%1$s ending %2$s</string>
<string name="shop_card_number_expires_on" formatted="false">Expires on %1$s/%2$s</string>
```

In my case, What I see is string for %1$s is being placed fine but %2$s shows memory location.

<img width="312" alt="Screenshot 2022-12-02 at 2 11 42 PM" src="https://user-images.githubusercontent.com/13232826/205252060-1401a10e-eba0-4f80-a7fb-ff98714b38e5.png">

**Comment by hansemannn** [comment]
This will be fixed by https://github.com/tidev/titanium_mobile/pull/13738

**Comment by m1ga** [comment]
PR was merged and issue is fixed with https://github.com/tidev/titanium-sdk/pull/13834
