### ISSUE TITLE
Android: update gradle

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-sdk#13579]
**Issue:** updateing to gradle > 7.1.0 breaks the SDK build.

Moving the other research parts into this ticket:

the compile errors start as soon as you go to `com.android.tools.build:gradle:7.1.0` (current SDK is using 7.0.4 - https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google)

version is set here: https://github.com/search?q=repo%3Atidev%2Ftitanium-sdk+com.android.tools.build%3Agradle%3A7.0.4&type=code (for app and modules)

more infos on gradle updates: https://github.com/tidev/titanium_mobile#upgrade-gradle-and-gradle-plugin

some other issues with gradle updates/infos:
* https://github.com/tidev/titanium_mobile/pull/13443
* https://github.com/tidev/titanium_mobile/pull/12914 (cmake update infos)
* https://github.com/tidev/titanium_mobile/pull/12821
* https://github.com/tidev/titanium_mobile/pull/12185
* my post in the gradle group: [link](https://discuss.gradle.org/t/build-order-problem-upgrading-build-tools-from-7-0-4-7-2-2/43850) 

removing 

https://github.com/tidev/titanium_mobile/blob/master/android/titanium/build.gradle#L67-L69 

and

https://github.com/tidev/titanium_mobile/blob/master/android/titanium/build.gradle#L76-L79

builds but of course breaks the SDK at the end. But it looks like those are the parts that will fail. It doesn't generate the files in `runtime/v8/generated` so `#include "org.appcelerator.kroll.KrollModule.h"` will fail during compiling. My guess is that the order of the gradle tasks changed and c++ are not generated before the cmake part

The gradle command `./gradlew :titanium:externalNativeBuildCleanDebug` will already trigger the error.

There is a google issue https://issuetracker.google.com/issues/232060576  **AGP 7.1 and higher does not build :nativelib module incrementally** with "As a workaround we are downgrading AGP." which looks like our issue too. I can remove the `.cxx` folder and the clean part works but then it breaks at `:titanium:buildCMakeRelWithDebInfo[arm64-v8a]` with `fatal error: 'org.appcelerator.kroll.KrollModule.h' file not found` since the files aren't there.

## Material lib version

The current version is 1.6.1. If we want to use >=1.7.0 (https://github.com/material-components/material-components-android/releases?expanded=true&page=2&q=1.7.0) we have to use a higher gradle-plugin version

**Comment by m1ga** [comment]
Interesting part:
if you use Studio to run the gradle task `:titanium:assembleRelease` it will still fail with the same error but continues with other task. After that you can run `npm run build` (without the clean) and the files are there.

so there is some kind of order error

**Comment by hansemannn** [comment]
cc @janvennemann

**Comment by AbdullahFaqeir** [comment]
CC @hansemannn @janvennemann @m1ga 

I would love to share this file with you guys after almost 40 hours of working and this is my third day awake.

[titanium-sdk-gradle-8.3.1-build.log](https://github.com/tidev/titanium-sdk/files/14687131/titanium-sdk-gradle-8.3.1-build.log)

I've upgraded Gradle version to the very latest 8.3.1 and I've completely fixed the tasks execution order along side some small fixes to deprecated apis.

**Comment by m1ga** [comment]
:open_mouth: sounds great! Besides the 3rd day awake part :smile:  Looking forward to test it!!!

**Comment by m1ga** [comment]
To make the real changes a bit easier to check later: 

can we merge this one first: https://github.com/tidev/titanium-sdk/pull/13888 ?
It is only applying Android Studio recommendations about the style:
```
    Consider using 'withType(...).configureEach' to avoid unnecessary configuration
    Consider using 'tasks.register' to avoid unnecessary configuration
```
no code changes in this PR but as this is part of the big gradle change coming up it will make it easier to test in steps.

And since there will be a CMake update too: https://github.com/tidev/titanium-sdk/pull/13966
**Don't worry:** looks big, but all Java files are just linting because I've raised `checkstyle` and it's a bit stricter now :smile:

**Comment by m1ga** [comment]
Huge congrats to @AbdullahFaqeir 🎉

The https://github.com/tidev/titanium-sdk/pull/14014 works! I was able to build kitchensink with it and my app that uses a few modules. I still have to do some more tests but the SDK builds :+1: 

Still would like to merge in stages so it's less to review and test. These would be my proposed order:
1. https://github.com/tidev/titanium-sdk/pull/13888 - styling recommendations
2. https://github.com/tidev/titanium-sdk/pull/13966 - cmake + checkstyle update
3. https://github.com/tidev/titanium-sdk/pull/14014 - his gradle stuff (will be a lot less changes when 1 is merged)
4. if we want: https://github.com/tidev/titanium-sdk/pull/13940 - so we can even use more modules (requires more testing, not required by the Playstore at the moment)

**Comment by trkfabi** [comment]
The [#14014](https://github.com/tidev/titanium-sdk/pull/14014) works for me! I was able to update a custom Android Stripe module using the latest Stripe SDK (which needs Material 1.11.0) and compile my app with the new Material theme, a new Gradle version and the compile target set to 34.
Minor issues with some UI components which I will try to workaround.

It would be great if this PR gets merged !

**Comment by trkfabi** [comment]
@hansemannn I just noticed that all the textfields' background are black now but I think this happens because I use a custom theme for this app which has not been updated in a while.

I found a workaround by adding a few lines to `/platform/android/res/values/mytheme.xml`:

```
<style name="Theme.NoActionBar" parent="@style/Theme.MaterialComponents">
        .... 
        ....

	<!-- Add custom text field styles -->
        <item name="textInputStyle">@style/CustomTextInputLayout</item>
</style>

  <!-- Custom style for TextInputLayout -->
  <style name="CustomTextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.FilledBox">
      <item name="boxBackgroundColor">#FFFFFF</item>
      <item name="hintTextColor">?attr/colorOnSurface</item>
      <item name="boxStrokeColor">?attr/colorPrimary</item>
  </style>
  <!-- Custom style for TextInputEditText -->
  <style name="CustomTextInputEditText" parent="Widget.MaterialComponents.TextInputEditText.FilledBox">
      <item name="android:background">#FFFFFF</item>
      <item name="android:textColor">?android:attr/textColorPrimary</item>
  </style>

```

So I guess this may not be an issue if you use a default Material theme.

**Comment by trkfabi** [comment]
@m1ga @hansemannn Everything looks good on the app except some `<TextField>` styling. 
The background was black as a I mentioned before and `backgroundColor` was not having effect, so I set a custom style with white background, but I realised that I need it to be gray in some places. This property is not working.
I had to add some custom style to change the `boxStrokeColor` property too to remove the black underline in the TextField and also change it to blue when focused. Is there a way to do this by code instead of messing with the theme?

`<item name="boxStrokeColor">@color/textinput_stroke_color</item>` and the text input_stroke_color file is:

```
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="#02B3E4" android:state_focused="true"/>
    <item android:color="#00FFFFFF" android:state_hovered="true"/>
    <item android:color="#00FFFFFF" android:state_enabled="false"/>
    <item android:color="#00FFFFFF"/>
</selector>
```

**Comment by m1ga** [comment]
I would need to look into that. There are some default styles for the Titanium themes. 

As mentioned in the older post I would start with the first two PRs (https://github.com/tidev/titanium-sdk/issues/13579#issuecomment-2021150043) before updating gradle. Those only update gradle syntax and cmake but still runs the old gradle and shouldn't break anything.

After those are merged the gradle PR is smaller and easier to see those style changes and how to fix those.

**Comment by trkfabi** [comment]
I was wondering the same as in line #190 hehe: https://github.com/tidev/titanium-sdk/blob/420ccdceadff8658803e02bb6144e853c8767a20/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiUIText.java#L189

If I change line #191 to `tv.setBackgroundColor(TiConvert.toColor(d, TiC.PROPERTY_BACKGROUND_COLOR, proxy.getActivity()));` it seems to work fine

**Comment by m1ga** [comment]
It looks like that was used to remove the underline: https://github.com/tidev/titanium-sdk/pull/9361#pullrequestreview-59011546
and search for `Will this remove the underline even if no custom background was applied?`
