### ISSUE TITLE
IOS 16: Default video controls missing

### ISSUE THREAD

**Issue by justingreerbbi** [tidev/titanium-sdk#13612]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When creating a video player using a local or remote source, the controls seem to be missing. 

IOS 16 introduced a new UX with video and while the Apple docs say that nothing else needs to happen on the developer side, it looks like there are indeed changes that need to be made.

An example of this issue with a possible fix can be found at https://stackoverflow.com/questions/72830620/playback-buttons-do-not-appear-in-an-avplayer-after-adding-a-layer-ios-16. 

It looks like the player controller needs to be added as a child to the parent before assigning the subview.

I am very new at the Ti Framework and have been attempting to patch this myself but I am lacking the experience for the framework currently to make the change.

### Expected Behavior

IOS 16 video player will display the IOS default UI when the video is tapped and scrubbed.

### Actual behavior

When the video player is tapped, no controls are displayed however the video event still works as expected.

### Reproducible sample

var vidWin = Titanium.UI.createWindow({
    title: 'Video View Demo',
    backgroundColor: '#fff'
});

var videoPlayer = Titanium.Media.createVideoPlayer({
    top: 2,
    autoplay: true,
    backgroundColor: 'blue',
    height: 300,
    width: 300,
    mediaControlStyle: Titanium.Media.VIDEO_CONTROL_DEFAULT,
    scalingMode: Titanium.Media.VIDEO_SCALING_RESIZE_ASPECT
});

videoPlayer.url = 'movie.mp4';
vidWin.add(videoPlayer);
vidWin.open();

### Steps to reproduce

Create a video player and once playing, tap the video to show controls.

### Platform

iOS

### SDK version you are using

11.1.1

**Comment by hansemannn** [comment]
It worked fine for me (tested with iOS 17 simulator), so it seems like they might fix it between iOS 16 and 17?
<img width="445" alt="Screenshot 2023-06-28 at 10 15 23" src="https://github.com/tidev/titanium-sdk/assets/10667698/58226bb0-51a5-4bb0-926b-0c70c6adb0d7">
