### ISSUE TITLE
iOS Ti.Media.openPhotoGallery saves selected video to inaccesible temp folder

### ISSUE THREAD

**Issue by FrancescoLombardo** [tidev/titanium-sdk#13620]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The blob retrieved using the below function, can be played using a videoPlayer but cannot be saved/copied anywhere else (in the app storage).

```
Ti.Media.openPhotoGallery({
  mediaTypes: [Ti.Media.MEDIA_TYPE_VIDEO],
  success: (e) => {
    blob = e.media;
  },
  ...
```

The blob nativePath is:
`file:///private/var/mobile/Containers/Data/PluginKitPlugin/E2DA5713-B3EE-4AA6-B33A-A9AB6AC620A4/tmp/trim.7340544C-0BAD-4534-9D09-908B65B8FDB6.MOV`

### Expected Behavior

The blob retrieved using Ti.Media.openPhotoGallery can be saved/copied in the app storage

### Actual behavior

Trying to save the blob using the standard method file.write(blob), produce this error (emoby.cloud is the name of my app):
`kernel(Sandbox)[0] <Error>: 1 duplicate report for Sandbox: emoby.cloud(18647) deny(1) file-read-data /private/var/mobile/Containers/Data/PluginKitPlugin/E2DA5713-B3EE-4AA6-B33A-A9AB6AC620A4/tmp/trim.7340544C-0BAD-4534-9D09-908B65B8FDB6.MOV`

Trying to save the blob using the code below, throws
`Error: TiStreamException. Attempt to read off of closed/nil data stream`

```
let inStream = Ti.Stream.createStream({ source: blob, mode: Ti.Stream.MODE_READ });
let outStream = f.open(Ti.Filesystem.MODE_WRITE);
let buffer = Ti.createBuffer({ length: 1024 });
let readBytes = 0;
while ((readBytes = inStream.read(buffer)) > 0) {
  outStream.write(buffer, 0, readBytes);
}
```

### Reproducible sample

```

let blob = null;

const saveBlob = () => {
  let dir = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, 'files');
  dir.createDirectory();
  dir = dir.nativePath + (dir.nativePath.slice(dir.nativePath.length-1) == '/' ? '' : '/') + 'testFile.mp4';
  let file = Ti.Filesystem.getFile(dir);
  file.write(blob);
};

Ti.Media.openPhotoGallery({
  mediaTypes: [Ti.Media.MEDIA_TYPE_VIDEO],
  autohide: true,
  success: (e) => {
    blob = e.media;
    // simulate wait for user interaction
    setTimeout(() => saveBlob(), 5000);
  },
});
```

### Steps to reproduce

Just use a real apple device

In my case i'm using an iPhone 13 Pro (iOS 15.7)

### Platform

iOS

### SDK version you are using

11.1.1.GA

### Alloy version you are using

1.0.1

**Comment by FrancescoLombardo** [comment]
Update: saving the blob immediately after the success callback, works without problems

**Comment by hansemannn** [comment]
Yep, this is actually intended behavior: For privacy reasons, the media is only available immediately after the selection, that's also why it's placed in the temporary folder, designed to behave like this.
