### ISSUE TITLE
iOS "longpress" event doesn't block the "click" event

### ISSUE THREAD

**Issue by FrancescoLombardo** [tidev/titanium-sdk#13637]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

iOS "longpress" event doesn't block the "click" event

### Expected Behavior

iOS "longpress" event block the "click" event, as in Android

### Actual behavior

iOS "longpress" event doesn't block the "click" event

### Reproducible sample

$.someView.addEventListener('longpress', async (e) => {
  console.log(e);
});

$.someView.addEventListener('click', async (e) => {
  console.log(e);
});

### Steps to reproduce

Long press the "someView" until it fires the "longpress" event, then lift the finger, now the click event will be fired

### Platform

iOS

### SDK version you are using

11.1.1.GA

### Alloy version you are using

1.0.1

**Comment by AbdullahFaqeir** [comment]
@hansemannn I believe my last fix to the click event would fix this since the click event back then used the touch event!

**Comment by hansemannn** [comment]
Great work!

**Comment by AbdullahFaqeir** [comment]
> Great work!

@hansemannn your appreciation keeps me going, I use almost all my free time for Ti!

**Comment by hansemannn** [comment]
Thats awesome. Your work makes the Titanium SDK better - keep up the good work!
