### ISSUE TITLE
iOS: ListViews headerView height is capped at screen height 

### ISSUE THREAD

**Issue by jonasfunk** [tidev/titanium-sdk#13718]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

HeaderView cannot be taller than screen height

### Expected Behavior

HeaderView should be able to be taller than screen height

### Actual behavior

HeaderView cannot be taller than screen height

### Reproducible sample

```
const win = Ti.UI.createWindow();

const headerView = Ti.UI.createView({ height: 3000, backgroundColor: 'red' });

const listView = Ti.UI.createListView({ 
	headerView,
	sections: [ Ti.UI.createListSection({ items: [ {properties: { title: 'Apple'}},{properties: { title: 'Banana'}} ] }) ]
 });
	

win.add(listView);

win.open();
```

### Steps to reproduce

Run code, and scroll the listview to see that headerViews height is not 3000, but capped at screen height. 

### SDK version you are using

12.0.0.GA.

### Alloy version you are using

2.0.1

**Comment by hansemannn** [comment]
Checking on iOS natively, this could be a native limitation of the UITableView, but I can check this further.

**Comment by jonasfunk** [comment]
Until now I've fixed it by modifying the `proxyDidRelayout` method of `TiUIListview.m`. It works, but since I have very limited knowledge of Obj C, I assume this is not the correct way to solve it. This is the code I use:

```
-(void)proxyDidRelayout:(id)sender
{
    TiThreadPerformOnMainThread(^{
        if (sender == _headerViewProxy) {
            UIView* headerView = [[self tableView] tableHeaderView];

            if (_headerWrapper != nil) {
                [headerView setFrame:[_headerWrapper view].frame];
                [[self tableView] setTableHeaderView:headerView];
            }
            else {
                [headerView setFrame:[headerView bounds]];

                [[self tableView] setTableHeaderView:headerView];
            }
            [((TiUIListViewProxy*)[self proxy]) contentsWillChange];
        } else if (sender == _footerViewProxy) {
            UIView *footerView = [[self tableView] tableFooterView];
            UIView* firstChild = [footerView.subviews objectAtIndex:0];
            CGRect footerViewFrame = footerView.frame;
            footerViewFrame.size.height = firstChild.bounds.size.height;
            footerView.frame = footerViewFrame;

            [[self tableView] setTableFooterView:footerView];
            [((TiUIListViewProxy*)[self proxy]) contentsWillChange];

        } else if (sender == _pullViewProxy) {
            pullThreshhold = ([_pullViewProxy view].frame.origin.y - _pullViewWrapper.bounds.size.height);
        }
    },NO);
}
```
I will just continue modifying the method per SDK version 👍

**Comment by hansemannn** [comment]
Okay, you override the frame manually by using the `_headerWrapper` bounds. Thats actually a smart move, but should usually not be natively possible. If you can work with that one for now, thats good! If you feel it should be part of the core SDK, please feel free to create a PR as well. Thank you! :-)

**Comment by hansemannn** [comment]
Okay, you override the frame manually by using the `_headerWrapper` bounds. Thats actually a smart move, but should usually not be natively possible. If you can work with that one for now, thats good! If you feel it should be part of the core SDK, please feel free to create a PR as well. Thank you! :-)
