### ISSUE TITLE
v8 snapshot server not available anymore

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-sdk#13906]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The old http://v8-snapshot.appcelerator.com/ server is not available anymore that served v8 snapshots to Mac/Windows machines when building the SDK for Android.

SDK location: https://github.com/tidev/titanium-sdk/blob/51c7c98afd69282c216c7a4fdfde1f5227032248/android/titanium/libv8-services.js#L176-L195

We are still at v8 8.8.278.17 (Ti 10.1.1.GA) because of a bug in 9.4 (https://github.com/tidev/titanium-sdk/issues/13395). I've fixed 9.4 (https://github.com/tidev/v8_titanium/pull/55) a year ago but the build action doesn't work anymore. 

v8 8.8.278.17  download:
https://github.com/tidev/v8_titanium/releases/tag/v8.8.278.17
but I'm not sure if that is the same as the snapshots from the v8-snapshot server.

### Expected Behavior

downloading a snapshot

### Actual behavior

failing after a few attempts

### Reproducible sample

go into `android/titanium` and run `node -e "require('./libv8-services').createSnapshotThenExit()"`

### Steps to reproduce

-

### Platform

Android

### SDK version you are using

12.3.0

**Comment by cb1kenobi** [comment]
Snapshot server is back! https://github.com/tidev/v8-snapshot-www

**Comment by cb1kenobi** [comment]
Fix https://github.com/tidev/titanium-sdk/pull/13907
