### ISSUE TITLE
Popover has glitch UI in iPadOS 17 and makes app freezing

### ISSUE THREAD

**Issue by AhmedMSayed** [tidev/titanium-sdk#13915]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Popover has glitch UI in iOS 17 something like padding (top, bottom padding if arrow Up or down || left, right padding if arrow left  or right) and makes app freezing when trying to open and hide it repeatedly, you will think that's not right way to open and close it repeatedly but in real project i have a lot of buttons which open a popover so when click on one of it and close to open another that will show glitch UI or makes app freezing.

### For first time
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 35](https://github.com/tidev/titanium-sdk/assets/7584480/78a5012f-3a3f-46f9-a579-794e1f5af0aa)

### After closing and opening
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 26](https://github.com/tidev/titanium-sdk/assets/7584480/e3410c82-5972-40b7-a907-6740d7d25faa)

### App freezing in opening popover
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 05](https://github.com/tidev/titanium-sdk/assets/7584480/98d544e5-47dd-4880-9288-faf6f9e68669)

### Reproducible sample

```
var popover;

const win = Ti.UI.createWindow();

const hidePopover = Ti.UI.createButton({
	title: 'Hide Popover',
	backgroundColor: 'orange',
	width: 160,
	height: 40
});
hidePopover.addEventListener("click", (e) => {
	popover.hide();
});

const showPopover = Ti.UI.createButton({
	title: "Show Popover",
	backgroundColor: 'red',
	width: 120,
	height: 40
});

showPopover.addEventListener("click", (e) => {
	const popoverWin = Ti.UI.createWindow({
		backgroundColor: 'red',
		title: 'Popover Window',
		rightNavButton: hidePopover
	});

	const listView = Ti.UI.createListView({
		backgroundColor: 'blue',
	});
	const sections = [];

	const fruitDataSet = [
		{ properties: { title: 'Apple' } },
		{ properties: { title: 'Banana' } },
	];
	const fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits', items: fruitDataSet });
	sections.push(fruitSection);

	const vegDataSet = [
		{ properties: { title: 'Carrots' } },
		{ properties: { title: 'Potatoes' } },
	];
	const vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables', items: vegDataSet });
	sections.push(vegSection);

	listView.sections = sections;

	popoverWin.add(listView);

	const fishDataSet = [
		{ properties: { title: 'Cod' } },
		{ properties: { title: 'Haddock' } },
	];
	const fishSection = Ti.UI.createListSection({ headerTitle: 'Fish', items: fishDataSet });
	listView.appendSection(fishSection);

	const popoverNav = Ti.UI.createNavigationWindow({
		window: popoverWin
	});

	popover = Ti.UI.iPad.createPopover({
		contentView: popoverNav
	});

	popover.show({ view: showPopover });
});

win.add(showPopover);

win.open();
```

### Steps to reproduce

1. create new classic app
2. add this sample code
3. click on showPopover button to show it
4. then click on hidePopover or outside the window
5. try to do this repeatedly

### Platform

iOS

### SDK version you are using

12.2.0

**Comment by AhmedMSayed** [comment]
Same Popover from my app

![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 57 12](https://github.com/tidev/titanium-sdk/assets/7584480/9c84f902-1a2c-4b0a-a7e2-49fd7f895809)
![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 57 57](https://github.com/tidev/titanium-sdk/assets/7584480/0254d490-0f8b-4e7f-90b8-36d1e9011e55)

**Comment by jsonengler** [comment]
I'm interested in getting this fix for my apps. would this go into a 12.2.1 release sometime in the future? is there any ETA on when it would be released?
