### ISSUE TITLE
Update titanium sdk returns Error

### ISSUE THREAD

**Issue by jadgerges** [tidev/titanium-sdk#13964]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

i am trying to update titanium sdk to 12.0.0.GA it returns the error below : 

**titanium sdk install 12.0.0.GA**
Titanium Command-Line Interface, CLI version 5.4.1, Titanium SDK version 10.1.1.GA
Copyright (c) 2012-2020, Appcelerator, Inc.  All Rights Reserved.

Please report bugs to https://github.com/appcelerator/titanium_mobile/issues

**[ERROR] Failed to retrieve release.
object null is not iterable (cannot read property Symbol(Symbol.iterator))**

### Expected Behavior

expected to update titanium mobile sdk

### Actual behavior

it returns a BUG

### Reproducible sample

try to update to sdk 12.0.0.GA from sdk 10.1.0.GA

### Steps to reproduce

try to update to sdk 12.0.0.GA from sdk 10.1.0.GA

### SDK version you are using

titanium sdk 10.1.1.GA (i updated in android studio to sdk 13)

### Alloy version you are using

alloy version 5.4.1

**Comment by m1ga** [comment]
That should be working again. We had some server issues which blocked downloads. They are up and running again.

Side note: 12.2.1.GA is the latest (12.3.0.RC will be out soon). So try to run that version right away.

**Comment by m1ga** [comment]
oh, and I just saw:
> Titanium Command-Line Interface, CLI version 5.4.1

You are running the old CLI! Please run `sudo npm i -g titanium alloy` to get the current CLI v6 version! That will download from Github. Your version tries to download from the old Appc servers

**Comment by m1ga** [comment]
@jadgerges is it fixed?

**Comment by jadgerges** [comment]
Hello,

The issue has been resolved by downloading it directly from https://github.com/tidev/titanium-sdk/releases/tag/12_2_1_GA

Thank you very much for your assistance.

Best regards,

**Comment by m1ga** [comment]
ok, it should also work when you update to the latest CLI as that will download the same file. `sudo npm i -g titanium alloy`

**Comment by jadgerges** [comment]
thank you, will check :)
