### ISSUE TITLE
is https://titaniumsdk.com/ down?

### ISSUE THREAD

**Issue by ganjarsetia** [tidev/titanium-sdk#13960]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### URL

https://titaniumsdk.com/

### Description

I want to read the docs & example but when I access https://titaniumsdk.com/ the web cant be opened.

![image](https://github.com/tidev/titanium-sdk/assets/3258090/7ceb2a38-cfa0-4317-aed0-910442e230df)

### Suggestion

Make it up again

**Comment by cb1kenobi** [comment]
Sorry! Site is back up!
