### ISSUE TITLE
Android: FAB tintColor

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-sdk#13971]
Reminder for myself: check FAB tintColor

### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Check FAB tintColor

### Platform

Android

### SDK version you are using

12.2.1

**Comment by Max87ZA** [comment]
I found [this](https://stackoverflow.com/a/53458899/4601786), so I tried to implement it into sdk, bot no luck so far...
My code:
`if (d.containsKey(TiC.PROPERTY_TINT_COLOR)) {`
`	setTintColor(d.getString("tintColor"), d.get(TiC.PROPERTY_IMAGE));`
`}`
and then

`public void setTintColor(String color, Object obj)`
`	{`
`		int tintColor = Color.parseColor(color);`
`		TiDrawableReference source = TiDrawableReference.fromObject(getProxy(), obj);`
`		Drawable icon = fab.getDrawable();`
`               icon.setColorFilter(tintColor, PorterDuff.Mode.SRC_IN);`
`		fab.setImageDrawable(source.getDrawable());`
`	}`

But it doesn't do anything, when I comment <item name="colorOnSecondary">#ffffff</item> in theme, icon remains black...

**Comment by m1ga** [comment]
Almost correct :smile: Here is a PR https://github.com/tidev/titanium-sdk/pull/13972
