### ISSUE TITLE
Camera View is reduced by half when using overlay with useCameraX 

### ISSUE THREAD

**Issue by cmtanko** [tidev/titanium-sdk#14064]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

PR: https://github.com/tidev/titanium-sdk/pull/12395

Even when using the sample code in the PR, and clicking 'open camera'. it loads up the camera, but half the height only. Unable to load the camera in fullscreen mode.
![Screenshot_20240613_224746](https://github.com/tidev/titanium-sdk/assets/9778829/c8129df5-dff5-488b-a868-573ffec5acb5)

Tried on various samsung & pixel devices.

### Expected Behavior

- Overlay view should be customisable to use fullscreen camera when using useCameraX.

### Actual behavior

- Whatever you do the camera wont open in fullScreen, if you useCameraX: false, then it goes to fullscreen.

### Reproducible sample

Follow the sample code: https://github.com/tidev/titanium-sdk/pull/12395

### Steps to reproduce

- click 'open camera' , 2nd button

### Platform

Android

### SDK version you are using

12.2.1.GA, 12.3.1.GA

### Alloy version you are using

2.1.0

**Comment by m1ga** [comment]
As discussed on Slack: new the code in a new project works fine so I'll close this as it looks like an user/app code related issue.
