### ISSUE TITLE
Undocumented responseDictionary attribute for HTTPClient Object

### ISSUE THREAD

**Issue by Informate** [tidev/titanium-sdk#14096]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### URL

https://titaniumsdk.com/api/titanium/network/httpclient.html

### Description

The responseDictionary attribute is not documented for the HTTPClient Object.
It returns a JSON representation of the response when response type is compatible with application/JSON. (On Android, untested on iOS)

### Suggestion

Report the feature

**Comment by m1ga** [comment]
PR https://github.com/tidev/titanium-sdk/pull/14101
