### ISSUE TITLE
Android: Sound volume property not working if set at creation time

### ISSUE THREAD

**Issue by Informate** [tidev/titanium-sdk#14108]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The sound volume property not working if set at creation time on Android

    const sound=Titanium.Media.createSound({ url, volume});
    
FIXING WORKAROUND:

Set it separately:

    sound.volume=volume;

### Expected Behavior

Set the sound volume

### Actual behavior

Play as 1 or as 0

### Reproducible sample

X

### Steps to reproduce

X

### Platform

Android

### SDK version you are using

12.4.0.GA

**Comment by m1ga** [comment]
working fine here
```js
var win = Ti.UI.createWindow();
var tf = Ti.UI.createTextField({value: "0.5"})

win.addEventListener("click", function() {
	var player = Ti.Media.createSound({
		url: "/boing.mp3",
		volume: tf.value
	});
	player.play();

})
win.add(tf);
win.open();
```

i can change the volume in the textfield and click in the window to play the sound. The volume is changing.

Tested with Ti 12.4.0.GA

**Comment by AbdullahFaqeir** [comment]
I'll take it from here

**Comment by m1ga** [comment]
@Informate  did you test the code and verify if it is working for you too?

**Comment by Informate** [comment]
I will do it as soon as I'll can. Anyway I found the volume problem inside a service. I'll make a deeper test but it will take some time.

**Comment by Informate** [comment]
I have done the test also on an unbinded service. Now all is working correctly! I don't know what was not working for me in the other case, but I experienced some problem with this feature.
You can mark this as not a bug! Happy for you, not so much for me :(

**Comment by Informate** [comment]
@m1ga I suppose the issue with the volume control is really present on the background service, but do not happen every time, it also happen more often especially on some device as a low-quality device (GoodTel - vendor ID 1f3a).
The background service today also played twice in parralel doubling the sounds ( How it works behind the lines is not fully clear to me or explained in the guide - my setInterval run the on the main app thread instead of in a separate context).

**Comment by m1ga** [comment]
maybe it depends on the Android SDK version? 

Background service: don't know, sorry. Not using those. Maybe you can either clear or check if it is already running using a Ti.App.property or a boolean value? Also make sure not to use Liveview while testing those parts as it might just be an issue there.
