### ISSUE TITLE
Notification Channel not up to date docs

### ISSUE THREAD

**Issue by Informate** [tidev/titanium-sdk#14106]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### URL

https://titaniumsdk.com/api/titanium/android/notificationchannel.html

### Description

In the example a non existent method getId is used, while the doc for the audioStreamType attribute seems merged into the importance attribute docs. The audioStreamType results undocumented and the correct availables values are unknown.

### Suggestion

X

**Comment by m1ga** [comment]
`getId()` is just `.id` now: https://titaniumsdk.com/api/titanium/android/notificationchannel.html#properties_id 
it's the old getter/setter update in Ti 10.

audiostreamtype is here: https://titaniumsdk.com/api/titanium/android/notification.html#audiostreamtype

You can also fork the repo and make the changes. Pull requests are always welcome!

**Comment by m1ga** [comment]
fix: https://github.com/tidev/titanium-sdk/pull/14107

**Comment by Informate** [comment]
Super fast fixing :)))

**Comment by m1ga** [comment]
No problem :smile: :+1:
