### ISSUE TITLE
Android CLI: Missing () in Error Reporting funciton

### ISSUE THREAD

**Issue by Informate** [tidev/titanium-sdk#14127]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Building I recived an error (over another Error)

[LiveView] TypeError: err.toString.split is not a function
    at /home/UserName/.titanium/mobilesdk/linux/12.5.0.GA/android/cli/hooks/run.js:90:20
    
 Change (android/cli/hooks/run.js, line 90):
 
  err.toString.split('\n').forEach(logger.error);
  
  in
  
  err.toString().split('\n').forEach(logger.error);

### Expected Behavior

X

### Actual behavior

X

### Reproducible sample

X

### Steps to reproduce

X

### Platform

CLI

### SDK version you are using

12.5.0

**Comment by cb1kenobi** [comment]
Whoops. My bad. What was I thinking.... 11 years ago! https://github.com/tidev/titanium-sdk/commit/a17e4df9ce774b068cf467a7e0b026b5eb9645d7

**Comment by m1ga** [comment]
> Whoops. My bad. What was I thinking.... 11 years ago! [a17e4df](https://github.com/tidev/titanium-sdk/commit/a17e4df9ce774b068cf467a7e0b026b5eb9645d7)

Guess nobody had the error case before :) But nice that it's fixed :+1:
