### ISSUE TITLE
Android: Andorid Studio build not finding XML files

### ISSUE THREAD

**Issue by m1ga** [tidev/titanium-sdk#14125]
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When trying to run the SDK `app.js` using Android Studio "play" it won't load any XML files e.g. themes. The error during build is:
`E  Package [com.titanium.test] reported as REPLACED, but missing application info. Assuming REMOVED.`
and when the app runs 
` W  (main) [14,47] Cannot find the theme: Theme.Titanium.Material3.DayNight`

It has todo with the gradle update so @AbdullahFaqeir you might know how to fix it right away :smile: 

### Expected Behavior

be able to use themes

### Actual behavior

no XML themes are found

### Reproducible sample

```js
var win1 = Ti.UI.createWindow({});
var tf = Ti.UI.createTextField({ bottom: 0, width: Ti.UI.FILL, borderWidth: 1, borderColor: "yellow"})
var win2 = Ti.UI.createWindow({});
win1.add(tf);

var tab1 = Ti.UI.createTab({ window: win1, title: 'Blue' }),
	tab2 = Ti.UI.createTab({ window: win2, title: 'Red'}),
	tabGroup = Ti.UI.createTabGroup({ tabs: [tab1, tab2],
		theme: "Theme.Titanium.Material3.DayNight",
		style: Titanium.UI.Android.TABS_STYLE_BOTTOM_NAVIGATION
	});
tabGroup.open();
```

### Steps to reproduce

* open `titanium-sdk/android` in Android Studio
* ctrl + shift + N and open `app.js`
* put the above code in there
* click the "Play" button

![Bildschirmfoto_20240928_143926](https://github.com/user-attachments/assets/f40a0a34-f69e-4dc0-baa9-b92bcfec9e54)

* open logcat and look at the output

![Bildschirmfoto_20240928_144001](https://github.com/user-attachments/assets/c21acda3-3598-4c97-84ad-d64423896d2b)

### Platform

Android

### SDK version you are using

12.6.0 / master

**Comment by AbdullahFaqeir** [comment]
I'll check this ASAP
